module.exports = {
  // Classifications
  RESERVED_WORD: 'PRE',
  IDENTIFIER: 'IDE',
  NUMBER: 'NRO',
  DELIMITER: 'DEL',
  ARITHMETIC_OPERATION: 'ART',
  RELATIONAL_OPERATION: 'REL',
  LOGIC_OPERATION: 'LOG',
  CHARACTER_SEQUENCE: 'CdC',

  // Errors
  UNDEFINED_LEXEME: 'NUL',
  MALFORMED_NUMBER: 'NMF',
  MALFORMED_SEQUENCE: 'CMF',
  MALFORMED_COMMENT: 'CoMF',
  MALFORMED_IDENTIFIER: 'IMF'
};